// This file was generated by 'update-profile.js'
/* eslint-disable */
module.exports = {
  "0.73": {
    "@elui-react-native/e2e-testing": {
      "name": "@elui-react-native/e2e-testing",
      "version": "1.40.8"
    },
    "@elui-react-native/tester": {
      "name": "@elui-react-native/tester",
      "version": "0.170.26"
    },
    "@elui-react-native/tester-win32": {
      "name": "@elui-react-native/tester-win32",
      "version": "0.38.43"
    },
    "@elui-react-native/avatar": {
      "name": "@elui-react-native/avatar",
      "version": "1.12.8"
    },
    "@elui-react-native/badge": {
      "name": "@elui-react-native/badge",
      "version": "0.11.2"
    },
    "@elui-react-native/button": {
      "name": "@elui-react-native/button",
      "version": "0.39.4"
    },
    "@elui-react-native/callout": {
      "name": "@elui-react-native/callout",
      "version": "0.27.2"
    },
    "@elui-react-native/checkbox": {
      "name": "@elui-react-native/checkbox",
      "version": "0.23.8"
    },
    "@elui-react-native/chip": {
      "name": "@elui-react-native/chip",
      "version": "0.4.8"
    },
    "@elui-react-native/contextual-menu": {
      "name": "@elui-react-native/contextual-menu",
      "version": "0.24.16"
    },
    "@elui-react-native/divider": {
      "name": "@elui-react-native/divider",
      "version": "0.7.8"
    },
    "@elui-react-native/focus-trap-zone": {
      "name": "@elui-react-native/focus-trap-zone",
      "version": "0.12.5"
    },
    "@elui-react-native/focus-zone": {
      "name": "@elui-react-native/focus-zone",
      "version": "0.21.0"
    },
    "@elui-react-native/icon": {
      "name": "@elui-react-native/icon",
      "version": "0.21.8"
    },
    "@elui-react-native/input": {
      "name": "@elui-react-native/input",
      "version": "0.7.8"
    },
    "@elui-react-native/link": {
      "name": "@elui-react-native/link",
      "version": "0.23.8"
    },
    "@elui-react-native/menu": {
      "name": "@elui-react-native/menu",
      "version": "1.14.22"
    },
    "@elui-react-native/menu-button": {
      "name": "@elui-react-native/menu-button",
      "version": "0.13.19"
    },
    "@elui-react-native/notification": {
      "name": "@elui-react-native/notification",
      "version": "0.25.11"
    },
    "@elui-react-native/persona": {
      "name": "@elui-react-native/persona",
      "version": "0.16.2"
    },
    "@elui-react-native/persona-coin": {
      "name": "@elui-react-native/persona-coin",
      "version": "0.15.2"
    },
    "@elui-react-native/pressable": {
      "name": "@elui-react-native/pressable",
      "version": "0.12.4"
    },
    "@elui-react-native/radio-group": {
      "name": "@elui-react-native/radio-group",
      "version": "0.21.16"
    },
    "@elui-react-native/separator": {
      "name": "@elui-react-native/separator",
      "version": "0.18.2"
    },
    "@elui-react-native/stack": {
      "name": "@elui-react-native/stack",
      "version": "0.10.7"
    },
    "@elui-react-native/switch": {
      "name": "@elui-react-native/switch",
      "version": "0.13.7"
    },
    "@elui-react-native/tablist": {
      "name": "@elui-react-native/tablist",
      "version": "0.7.4"
    },
    "@elui-react-native/text": {
      "name": "@elui-react-native/text",
      "version": "0.24.6"
    },
    "@uifabricshared/foundation-composable": {
      "name": "@uifabricshared/foundation-composable",
      "version": "0.13.1"
    },
    "@uifabricshared/foundation-compose": {
      "name": "@uifabricshared/foundation-compose",
      "version": "1.15.2"
    },
    "@uifabricshared/foundation-settings": {
      "name": "@uifabricshared/foundation-settings",
      "version": "0.15.1"
    },
    "@uifabricshared/foundation-tokens": {
      "name": "@uifabricshared/foundation-tokens",
      "version": "0.15.2"
    },
    "@uifabricshared/theme-registry": {
      "name": "@uifabricshared/theme-registry",
      "version": "0.12.0"
    },
    "@uifabricshared/themed-settings": {
      "name": "@uifabricshared/themed-settings",
      "version": "0.12.1"
    },
    "@uifabricshared/theming-ramp": {
      "name": "@uifabricshared/theming-ramp",
      "version": "0.20.2"
    },
    "@uifabricshared/theming-react-native": {
      "name": "@uifabricshared/theming-react-native",
      "version": "0.20.5"
    },
    "@elui-react-native/experimental-activity-indicator": {
      "name": "@elui-react-native/experimental-activity-indicator",
      "version": "0.10.3"
    },
    "@elui-react-native/experimental-appearance-additions": {
      "name": "@elui-react-native/experimental-appearance-additions",
      "version": "0.7.2"
    },
    "@elui-react-native/experimental-avatar": {
      "name": "@elui-react-native/experimental-avatar",
      "version": "0.21.4"
    },
    "@elui-react-native/experimental-checkbox": {
      "name": "@elui-react-native/experimental-checkbox",
      "version": "0.17.9"
    },
    "@elui-react-native/drawer": {
      "name": "@elui-react-native/drawer",
      "version": "0.4.4"
    },
    "@elui-react-native/dropdown": {
      "name": "@elui-react-native/dropdown",
      "version": "0.10.13"
    },
    "@elui-react-native/experimental-expander": {
      "name": "@elui-react-native/experimental-expander",
      "version": "0.8.3"
    },
    "@elui-react-native/experimental-menu-button": {
      "name": "@elui-react-native/experimental-menu-button",
      "version": "0.10.19"
    },
    "@elui-react-native/experimental-native-date-picker": {
      "name": "@elui-react-native/experimental-native-date-picker",
      "version": "0.11.0"
    },
    "@elui-react-native/experimental-native-font-metrics": {
      "name": "@elui-react-native/experimental-native-font-metrics",
      "version": "0.6.0"
    },
    "@elui-react-native/overflow": {
      "name": "@elui-react-native/overflow",
      "version": "0.3.22"
    },
    "@elui-react-native/popover": {
      "name": "@elui-react-native/popover",
      "version": "0.4.2"
    },
    "@elui-react-native/experimental-shadow": {
      "name": "@elui-react-native/experimental-shadow",
      "version": "0.6.4"
    },
    "@elui-react-native/experimental-shimmer": {
      "name": "@elui-react-native/experimental-shimmer",
      "version": "0.13.5"
    },
    "@elui-react-native/spinner": {
      "name": "@elui-react-native/spinner",
      "version": "0.9.9"
    },
    "@elui-react-native/tooltip": {
      "name": "@elui-react-native/tooltip",
      "version": "0.4.11"
    },
    "@elui-react-native/vibrancy-view": {
      "name": "@elui-react-native/vibrancy-view",
      "version": "0.3.0"
    },
    "@elui-react-native/composition": {
      "name": "@elui-react-native/composition",
      "version": "0.11.2"
    },
    "@elui-react-native/eslint-config-rules": {
      "name": "@elui-react-native/eslint-config-rules",
      "version": "0.1.1"
    },
    "@elui-react-native/framework": {
      "name": "@elui-react-native/framework",
      "version": "0.14.2"
    },
    "@elui-react-native/immutable-merge": {
      "name": "@elui-react-native/immutable-merge",
      "version": "1.2.2"
    },
    "@elui-react-native/memo-cache": {
      "name": "@elui-react-native/memo-cache",
      "version": "1.3.3"
    },
    "@elui-react-native/merge-props": {
      "name": "@elui-react-native/merge-props",
      "version": "0.9.1"
    },
    "@elui-react-native/theme": {
      "name": "@elui-react-native/theme",
      "version": "0.11.1"
    },
    "@elui-react-native/themed-stylesheet": {
      "name": "@elui-react-native/themed-stylesheet",
      "version": "1.7.1"
    },
    "@elui-react-native/use-slot": {
      "name": "@elui-react-native/use-slot",
      "version": "0.6.2"
    },
    "@elui-react-native/use-slots": {
      "name": "@elui-react-native/use-slots",
      "version": "0.10.2"
    },
    "@elui-react-native/use-styling": {
      "name": "@elui-react-native/use-styling",
      "version": "0.13.2"
    },
    "@elui-react-native/use-tokens": {
      "name": "@elui-react-native/use-tokens",
      "version": "0.6.2"
    },
    "@elui/react-native": {
      "name": "@elui/react-native",
      "version": "0.42.13"
    },
    "@elui-react-native/android-theme": {
      "name": "@elui-react-native/android-theme",
      "version": "0.25.2"
    },
    "@elui-react-native/apple-theme": {
      "name": "@elui-react-native/apple-theme",
      "version": "0.28.2"
    },
    "@elui-react-native/default-theme": {
      "name": "@elui-react-native/default-theme",
      "version": "0.26.2"
    },
    "@elui-react-native/theme-tokens": {
      "name": "@elui-react-native/theme-tokens",
      "version": "0.27.1"
    },
    "@elui-react-native/theme-types": {
      "name": "@elui-react-native/theme-types",
      "version": "0.39.1"
    },
    "@elui-react-native/theming-utils": {
      "name": "@elui-react-native/theming-utils",
      "version": "0.26.1"
    },
    "@elui-react-native/win32-theme": {
      "name": "@elui-react-native/win32-theme",
      "version": "0.34.5"
    },
    "@elui-react-native/adapters": {
      "name": "@elui-react-native/adapters",
      "version": "0.13.0"
    },
    "@elui-react-native/interactive-hooks": {
      "name": "@elui-react-native/interactive-hooks",
      "version": "0.27.4"
    },
    "@elui-react-native/styling-utils": {
      "name": "@elui-react-native/styling-utils",
      "version": "0.7.0"
    },
    "@elui-react-native/tokens": {
      "name": "@elui-react-native/tokens",
      "version": "0.23.1"
    }
  },
  "0.72": {
    "@elui-react-native/e2e-testing": {
      "name": "@elui-react-native/e2e-testing",
      "version": "1.34.19"
    },
    "@elui-react-native/tester": {
      "name": "@elui-react-native/tester",
      "version": "0.167.33"
    },
    "@elui-react-native/tester-win32": {
      "name": "@elui-react-native/tester-win32",
      "version": "0.37.64"
    },
    "@elui-react-native/avatar": {
      "name": "@elui-react-native/avatar",
      "version": "1.11.15"
    },
    "@elui-react-native/badge": {
      "name": "@elui-react-native/badge",
      "version": "0.8.15"
    },
    "@elui-react-native/button": {
      "name": "@elui-react-native/button",
      "version": "0.36.18"
    },
    "@elui-react-native/callout": {
      "name": "@elui-react-native/callout",
      "version": "0.25.16"
    },
    "@elui-react-native/checkbox": {
      "name": "@elui-react-native/checkbox",
      "version": "0.22.14"
    },
    "@elui-react-native/chip": {
      "name": "@elui-react-native/chip",
      "version": "0.3.15"
    },
    "@elui-react-native/contextual-menu": {
      "name": "@elui-react-native/contextual-menu",
      "version": "0.23.19"
    },
    "@elui-react-native/divider": {
      "name": "@elui-react-native/divider",
      "version": "0.6.15"
    },
    "@elui-react-native/focus-trap-zone": {
      "name": "@elui-react-native/focus-trap-zone",
      "version": "0.11.15"
    },
    "@elui-react-native/focus-zone": {
      "name": "@elui-react-native/focus-zone",
      "version": "0.16.15"
    },
    "@elui-react-native/icon": {
      "name": "@elui-react-native/icon",
      "version": "0.20.15"
    },
    "@elui-react-native/input": {
      "name": "@elui-react-native/input",
      "version": "0.6.5"
    },
    "@elui-react-native/link": {
      "name": "@elui-react-native/link",
      "version": "0.21.14"
    },
    "@elui-react-native/menu": {
      "name": "@elui-react-native/menu",
      "version": "1.13.2"
    },
    "@elui-react-native/menu-button": {
      "name": "@elui-react-native/menu-button",
      "version": "0.12.22"
    },
    "@elui-react-native/notification": {
      "name": "@elui-react-native/notification",
      "version": "0.24.18"
    },
    "@elui-react-native/persona": {
      "name": "@elui-react-native/persona",
      "version": "0.15.12"
    },
    "@elui-react-native/persona-coin": {
      "name": "@elui-react-native/persona-coin",
      "version": "0.14.12"
    },
    "@elui-react-native/pressable": {
      "name": "@elui-react-native/pressable",
      "version": "0.11.14"
    },
    "@elui-react-native/radio-group": {
      "name": "@elui-react-native/radio-group",
      "version": "0.20.17"
    },
    "@elui-react-native/separator": {
      "name": "@elui-react-native/separator",
      "version": "0.17.11"
    },
    "@elui-react-native/stack": {
      "name": "@elui-react-native/stack",
      "version": "0.9.14"
    },
    "@elui-react-native/switch": {
      "name": "@elui-react-native/switch",
      "version": "0.12.14"
    },
    "@elui-react-native/tablist": {
      "name": "@elui-react-native/tablist",
      "version": "0.5.23"
    },
    "@elui-react-native/text": {
      "name": "@elui-react-native/text",
      "version": "0.22.14"
    },
    "@uifabricshared/foundation-composable": {
      "name": "@uifabricshared/foundation-composable",
      "version": "0.12.5"
    },
    "@uifabricshared/foundation-compose": {
      "name": "@uifabricshared/foundation-compose",
      "version": "1.14.25"
    },
    "@uifabricshared/foundation-settings": {
      "name": "@uifabricshared/foundation-settings",
      "version": "0.14.1"
    },
    "@uifabricshared/foundation-tokens": {
      "name": "@uifabricshared/foundation-tokens",
      "version": "0.14.9"
    },
    "@uifabricshared/theme-registry": {
      "name": "@uifabricshared/theme-registry",
      "version": "0.11.2"
    },
    "@uifabricshared/themed-settings": {
      "name": "@uifabricshared/themed-settings",
      "version": "0.11.1"
    },
    "@uifabricshared/theming-ramp": {
      "name": "@uifabricshared/theming-ramp",
      "version": "0.19.12"
    },
    "@uifabricshared/theming-react-native": {
      "name": "@uifabricshared/theming-react-native",
      "version": "0.19.13"
    },
    "@elui-react-native/experimental-activity-indicator": {
      "name": "@elui-react-native/experimental-activity-indicator",
      "version": "0.9.11"
    },
    "@elui-react-native/experimental-appearance-additions": {
      "name": "@elui-react-native/experimental-appearance-additions",
      "version": "0.6.11"
    },
    "@elui-react-native/experimental-avatar": {
      "name": "@elui-react-native/experimental-avatar",
      "version": "0.20.13"
    },
    "@elui-react-native/experimental-checkbox": {
      "name": "@elui-react-native/experimental-checkbox",
      "version": "0.16.15"
    },
    "@elui-react-native/drawer": {
      "name": "@elui-react-native/drawer",
      "version": "0.3.13"
    },
    "@elui-react-native/dropdown": {
      "name": "@elui-react-native/dropdown",
      "version": "0.9.20"
    },
    "@elui-react-native/experimental-expander": {
      "name": "@elui-react-native/experimental-expander",
      "version": "0.7.13"
    },
    "@elui-react-native/experimental-menu-button": {
      "name": "@elui-react-native/experimental-menu-button",
      "version": "0.9.21"
    },
    "@elui-react-native/experimental-native-date-picker": {
      "name": "@elui-react-native/experimental-native-date-picker",
      "version": "0.10.1"
    },
    "@elui-react-native/experimental-native-font-metrics": {
      "name": "@elui-react-native/experimental-native-font-metrics",
      "version": "0.5.1"
    },
    "@elui-react-native/overflow": {
      "name": "@elui-react-native/overflow",
      "version": "0.2.10"
    },
    "@elui-react-native/popover": {
      "name": "@elui-react-native/popover",
      "version": "0.3.11"
    },
    "@elui-react-native/experimental-shadow": {
      "name": "@elui-react-native/experimental-shadow",
      "version": "0.5.14"
    },
    "@elui-react-native/experimental-shimmer": {
      "name": "@elui-react-native/experimental-shimmer",
      "version": "0.12.15"
    },
    "@elui-react-native/spinner": {
      "name": "@elui-react-native/spinner",
      "version": "0.8.15"
    },
    "@elui-react-native/tooltip": {
      "name": "@elui-react-native/tooltip",
      "version": "0.2.19"
    },
    "@elui-react-native/vibrancy-view": {
      "name": "@elui-react-native/vibrancy-view",
      "version": "0.1.5"
    },
    "@elui-react-native/composition": {
      "name": "@elui-react-native/composition",
      "version": "0.10.2"
    },
    "@elui-react-native/eslint-config-rules": {
      "name": "@elui-react-native/eslint-config-rules",
      "version": "0.1.1"
    },
    "@elui-react-native/framework": {
      "name": "@elui-react-native/framework",
      "version": "0.13.10"
    },
    "@elui-react-native/immutable-merge": {
      "name": "@elui-react-native/immutable-merge",
      "version": "1.2.2"
    },
    "@elui-react-native/memo-cache": {
      "name": "@elui-react-native/memo-cache",
      "version": "1.3.2"
    },
    "@elui-react-native/merge-props": {
      "name": "@elui-react-native/merge-props",
      "version": "0.8.1"
    },
    "@elui-react-native/theme": {
      "name": "@elui-react-native/theme",
      "version": "0.10.8"
    },
    "@elui-react-native/themed-stylesheet": {
      "name": "@elui-react-native/themed-stylesheet",
      "version": "1.6.1"
    },
    "@elui-react-native/use-slot": {
      "name": "@elui-react-native/use-slot",
      "version": "0.5.2"
    },
    "@elui-react-native/use-slots": {
      "name": "@elui-react-native/use-slots",
      "version": "0.9.2"
    },
    "@elui-react-native/use-styling": {
      "name": "@elui-react-native/use-styling",
      "version": "0.12.1"
    },
    "@elui-react-native/use-tokens": {
      "name": "@elui-react-native/use-tokens",
      "version": "0.5.1"
    },
    "@elui/react-native": {
      "name": "@elui/react-native",
      "version": "0.40.12"
    },
    "@elui-react-native/android-theme": {
      "name": "@elui-react-native/android-theme",
      "version": "0.24.5"
    },
    "@elui-react-native/apple-theme": {
      "name": "@elui-react-native/apple-theme",
      "version": "0.27.5"
    },
    "@elui-react-native/default-theme": {
      "name": "@elui-react-native/default-theme",
      "version": "0.25.5"
    },
    "@elui-react-native/theme-tokens": {
      "name": "@elui-react-native/theme-tokens",
      "version": "0.26.7"
    },
    "@elui-react-native/theme-types": {
      "name": "@elui-react-native/theme-types",
      "version": "0.38.1"
    },
    "@elui-react-native/theming-utils": {
      "name": "@elui-react-native/theming-utils",
      "version": "0.25.9"
    },
    "@elui-react-native/win32-theme": {
      "name": "@elui-react-native/win32-theme",
      "version": "0.33.5"
    },
    "@elui-react-native/adapters": {
      "name": "@elui-react-native/adapters",
      "version": "0.12.3"
    },
    "@elui-react-native/interactive-hooks": {
      "name": "@elui-react-native/interactive-hooks",
      "version": "0.26.4"
    },
    "@elui-react-native/styling-utils": {
      "name": "@elui-react-native/styling-utils",
      "version": "0.6.1"
    },
    "@elui-react-native/tokens": {
      "name": "@elui-react-native/tokens",
      "version": "0.22.9"
    }
  },
  "0.71": {
    "@elui-react-native/e2e-testing": {
      "name": "@elui-react-native/e2e-testing",
      "version": "1.32.8"
    },
    "@elui-react-native/tester": {
      "name": "@elui-react-native/tester",
      "version": "0.157.10"
    },
    "@elui-react-native/tester-win32": {
      "name": "@elui-react-native/tester-win32",
      "version": "0.36.17"
    },
    "@elui-react-native/avatar": {
      "name": "@elui-react-native/avatar",
      "version": "1.10.18"
    },
    "@elui-react-native/badge": {
      "name": "@elui-react-native/badge",
      "version": "0.7.14"
    },
    "@elui-react-native/button": {
      "name": "@elui-react-native/button",
      "version": "0.35.11"
    },
    "@elui-react-native/callout": {
      "name": "@elui-react-native/callout",
      "version": "0.24.19"
    },
    "@elui-react-native/checkbox": {
      "name": "@elui-react-native/checkbox",
      "version": "0.21.7"
    },
    "@elui-react-native/chip": {
      "name": "@elui-react-native/chip",
      "version": "0.2.9"
    },
    "@elui-react-native/contextual-menu": {
      "name": "@elui-react-native/contextual-menu",
      "version": "0.22.25"
    },
    "@elui-react-native/divider": {
      "name": "@elui-react-native/divider",
      "version": "0.5.16"
    },
    "@elui-react-native/focus-trap-zone": {
      "name": "@elui-react-native/focus-trap-zone",
      "version": "0.10.14"
    },
    "@elui-react-native/focus-zone": {
      "name": "@elui-react-native/focus-zone",
      "version": "0.15.0"
    },
    "@elui-react-native/icon": {
      "name": "@elui-react-native/icon",
      "version": "0.19.16"
    },
    "@elui-react-native/input": {
      "name": "@elui-react-native/input",
      "version": "0.4.9"
    },
    "@elui-react-native/link": {
      "name": "@elui-react-native/link",
      "version": "0.20.7"
    },
    "@elui-react-native/menu": {
      "name": "@elui-react-native/menu",
      "version": "1.11.30"
    },
    "@elui-react-native/menu-button": {
      "name": "@elui-react-native/menu-button",
      "version": "0.11.31"
    },
    "@elui-react-native/notification": {
      "name": "@elui-react-native/notification",
      "version": "0.23.22"
    },
    "@elui-react-native/persona": {
      "name": "@elui-react-native/persona",
      "version": "0.14.12"
    },
    "@elui-react-native/persona-coin": {
      "name": "@elui-react-native/persona-coin",
      "version": "0.13.12"
    },
    "@elui-react-native/pressable": {
      "name": "@elui-react-native/pressable",
      "version": "0.10.13"
    },
    "@elui-react-native/radio-group": {
      "name": "@elui-react-native/radio-group",
      "version": "0.19.9"
    },
    "@elui-react-native/separator": {
      "name": "@elui-react-native/separator",
      "version": "0.16.10"
    },
    "@elui-react-native/stack": {
      "name": "@elui-react-native/stack",
      "version": "0.8.16"
    },
    "@elui-react-native/switch": {
      "name": "@elui-react-native/switch",
      "version": "0.11.7"
    },
    "@elui-react-native/text": {
      "name": "@elui-react-native/text",
      "version": "0.21.14"
    },
    "@uifabricshared/foundation-composable": {
      "name": "@uifabricshared/foundation-composable",
      "version": "0.12.2"
    },
    "@uifabricshared/foundation-compose": {
      "name": "@uifabricshared/foundation-compose",
      "version": "1.14.12"
    },
    "@uifabricshared/foundation-settings": {
      "name": "@uifabricshared/foundation-settings",
      "version": "0.13.2"
    },
    "@uifabricshared/foundation-tokens": {
      "name": "@uifabricshared/foundation-tokens",
      "version": "0.13.9"
    },
    "@uifabricshared/theme-registry": {
      "name": "@uifabricshared/theme-registry",
      "version": "0.10.1"
    },
    "@uifabricshared/themed-settings": {
      "name": "@uifabricshared/themed-settings",
      "version": "0.10.2"
    },
    "@uifabricshared/theming-ramp": {
      "name": "@uifabricshared/theming-ramp",
      "version": "0.19.4"
    },
    "@uifabricshared/theming-react-native": {
      "name": "@uifabricshared/theming-react-native",
      "version": "0.18.12"
    },
    "@elui-react-native/experimental-activity-indicator": {
      "name": "@elui-react-native/experimental-activity-indicator",
      "version": "0.8.12"
    },
    "@elui-react-native/experimental-appearance-additions": {
      "name": "@elui-react-native/experimental-appearance-additions",
      "version": "0.5.12"
    },
    "@elui-react-native/experimental-avatar": {
      "name": "@elui-react-native/experimental-avatar",
      "version": "0.19.11"
    },
    "@elui-react-native/experimental-button": {
      "name": "@elui-react-native/experimental-button",
      "version": "0.18.22"
    },
    "@elui-react-native/experimental-checkbox": {
      "name": "@elui-react-native/experimental-checkbox",
      "version": "0.15.17"
    },
    "@elui-react-native/drawer": {
      "name": "@elui-react-native/drawer",
      "version": "0.2.13"
    },
    "@elui-react-native/dropdown": {
      "name": "@elui-react-native/dropdown",
      "version": "0.8.29"
    },
    "@elui-react-native/experimental-expander": {
      "name": "@elui-react-native/experimental-expander",
      "version": "0.6.13"
    },
    "@elui-react-native/experimental-link": {
      "name": "@elui-react-native/experimental-link",
      "version": "0.6.16"
    },
    "@elui-react-native/experimental-menu-button": {
      "name": "@elui-react-native/experimental-menu-button",
      "version": "0.7.31"
    },
    "@elui-react-native/experimental-native-date-picker": {
      "name": "@elui-react-native/experimental-native-date-picker",
      "version": "0.9.1"
    },
    "@elui-react-native/experimental-native-font-metrics": {
      "name": "@elui-react-native/experimental-native-font-metrics",
      "version": "0.4.1"
    },
    "@elui-react-native/popover": {
      "name": "@elui-react-native/popover",
      "version": "0.2.11"
    },
    "@elui-react-native/experimental-radio-group": {
      "name": "@elui-react-native/experimental-radio-group",
      "version": "0.11.19"
    },
    "@elui-react-native/experimental-shadow": {
      "name": "@elui-react-native/experimental-shadow",
      "version": "0.4.12"
    },
    "@elui-react-native/experimental-shimmer": {
      "name": "@elui-react-native/experimental-shimmer",
      "version": "0.11.6"
    },
    "@elui-react-native/spinner": {
      "name": "@elui-react-native/spinner",
      "version": "0.7.15"
    },
    "@elui-react-native/tablist": {
      "name": "@elui-react-native/tablist",
      "version": "0.4.10"
    },
    "@elui-react-native/experimental-text": {
      "name": "@elui-react-native/experimental-text",
      "version": "0.13.14"
    },
    "@elui-react-native/vibrancy-view": {
      "name": "@elui-react-native/vibrancy-view",
      "version": "0.0.3"
    },
    "@elui-react-native/component-cache": {
      "name": "@elui-react-native/component-cache",
      "version": "1.5.1"
    },
    "@elui-react-native/composition": {
      "name": "@elui-react-native/composition",
      "version": "0.9.2"
    },
    "@elui-react-native/eslint-config-rules": {
      "name": "@elui-react-native/eslint-config-rules",
      "version": "0.1.1"
    },
    "@elui-react-native/framework": {
      "name": "@elui-react-native/framework",
      "version": "0.11.10"
    },
    "@elui-react-native/immutable-merge": {
      "name": "@elui-react-native/immutable-merge",
      "version": "1.2.1"
    },
    "@elui-react-native/memo-cache": {
      "name": "@elui-react-native/memo-cache",
      "version": "1.3.1"
    },
    "@elui-react-native/merge-props": {
      "name": "@elui-react-native/merge-props",
      "version": "0.7.1"
    },
    "@elui-react-native/theme": {
      "name": "@elui-react-native/theme",
      "version": "0.9.4"
    },
    "@elui-react-native/themed-stylesheet": {
      "name": "@elui-react-native/themed-stylesheet",
      "version": "1.5.2"
    },
    "@elui-react-native/use-slot": {
      "name": "@elui-react-native/use-slot",
      "version": "0.4.2"
    },
    "@elui-react-native/use-slots": {
      "name": "@elui-react-native/use-slots",
      "version": "0.8.2"
    },
    "@elui-react-native/use-styling": {
      "name": "@elui-react-native/use-styling",
      "version": "0.11.1"
    },
    "@elui-react-native/use-tokens": {
      "name": "@elui-react-native/use-tokens",
      "version": "0.4.2"
    },
    "@elui/react-native": {
      "name": "@elui/react-native",
      "version": "0.38.6"
    },
    "@elui-react-native/android-theme": {
      "name": "@elui-react-native/android-theme",
      "version": "0.18.9"
    },
    "@elui-react-native/apple-theme": {
      "name": "@elui-react-native/apple-theme",
      "version": "0.21.13"
    },
    "@elui-react-native/default-theme": {
      "name": "@elui-react-native/default-theme",
      "version": "0.19.11"
    },
    "@elui-react-native/theme-tokens": {
      "name": "@elui-react-native/theme-tokens",
      "version": "0.25.4"
    },
    "@elui-react-native/theme-types": {
      "name": "@elui-react-native/theme-types",
      "version": "0.32.3"
    },
    "@elui-react-native/theming-utils": {
      "name": "@elui-react-native/theming-utils",
      "version": "0.24.7"
    },
    "@elui-react-native/win32-theme": {
      "name": "@elui-react-native/win32-theme",
      "version": "0.27.10"
    },
    "@elui-react-native/adapters": {
      "name": "@elui-react-native/adapters",
      "version": "0.11.3"
    },
    "@elui-react-native/interactive-hooks": {
      "name": "@elui-react-native/interactive-hooks",
      "version": "0.24.12"
    },
    "@elui-react-native/styling-utils": {
      "name": "@elui-react-native/styling-utils",
      "version": "0.5.0"
    },
    "@elui-react-native/tokens": {
      "name": "@elui-react-native/tokens",
      "version": "0.21.6"
    }
  }
};
